---
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Docker CI
on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker

    steps:
      # https://github.com/marketplace/actions/checkout
      # - name: Build the Docker image
      #   uses: actions/checkout@v6.0.2
      #   run: docker build . --file Dockerfile --tag raneto/raneto:latest-$(date +%s)

      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      # https://github.com/marketplace/actions/docker-login
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      - name: Build and push
        uses: docker/build-push-action@v6.19.2
        with:
          #context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: raneto/raneto:unstable
